### ISSUE TITLE
Never Die

### ISSUE THREAD

**Issue by tkiral** [benmwebb/dopewars#70]
Not sure if this is intentional, but when playing the mac terminal version of the game, the game doesn't end when you lose all your health, you just continue the game at 100 health.

**Comment by benmwebb** [comment]
Are you playing in antique mode (`-a` switch)? If so then this would be a bug - you are certainly supposed to die at zero health. If not, when you reach zero health you merely lose a helper/bitch and thus inventory space. Only when you've lost all helpers will you take damage yourself.

**Comment by tkiral** [comment]
Ah ok, my mistake. Not a bug from what I've seen then.
